### Sudoku Solver

Utlising back-tracking to solve sudoku puzzles- based off of the [Computerphile video](https://www.youtube.com/watch?v=G_UYXzGuqvM)

In [3]:
import numpy as np

grid = [
    [5,3,0,0,7,0,0,0,0],
    [6,0,0,1,9,5,0,0,0],
    [0,9,8,0,0,0,0,6,0],
    [8,0,0,0,6,0,0,0,3],
    [4,0,0,8,0,3,0,0,1],
    [7,0,0,0,2,0,0,0,6],
    [0,6,0,0,0,0,2,8,0],
    [0,0,0,4,1,9,0,0,5],
    [0,0,0,0,8,0,0,7,9],
    ]


def possible(r,c,n):
    global grid

    # Check if n in row
    for i in range(9):
        if grid[r][i] == n : return False

    # Check if n in column.
    for i in range(9):
        if grid[i][c] == n : return False

    # Check if n in 3x3 square.
    r0 = (r // 3) * 3
    c0 = (c // 3) * 3
    for i in range(3):
        for j in range(3):
            if grid[r0+i][c0+j] == n : return False
    
    return True


def solve():
    global grid
    for r in range(9):
        for c in range(9):
            if grid[r][c] == 0:
                for n in range(1,10):
                    if possible(r,c,n):
                        grid[r][c] = n
                        solve()
                        
                        # Back-track here
                        grid[r][c] = 0
                return
    print(np.matrix(grid))


In [4]:
solve()

[[5 3 4 6 7 8 9 1 2]
 [6 7 2 1 9 5 3 4 8]
 [1 9 8 3 4 2 5 6 7]
 [8 5 9 7 6 1 4 2 3]
 [4 2 6 8 5 3 7 9 1]
 [7 1 3 9 2 4 8 5 6]
 [9 6 1 5 3 7 2 8 4]
 [2 8 7 4 1 9 6 3 5]
 [3 4 5 2 8 6 1 7 9]]
